// <auto-generated />
using System;
using System.Collections.Generic;
using Brewbook.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Brewbook.Api.Data.Migrations
{
    [DbContext(typeof(BrewbookDbContext))]
    [Migration("20260901195450_OnboardingSeen")]
    partial class OnboardingSeen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Brewbook.Api.Domain.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Altitude")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("DeclaredNotes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("LabelScanId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LabelScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Origin")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Process")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Producer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("RoastDate")
                        .HasColumnType("date");

                    b.Property<string>("RoastLevel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Roaster")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Varietal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Archived");

                    b.ToTable("beans", (string)null);
                });

            modelBuilder.Entity("Brewbook.Api.Domain.Brew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Blooms")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BrewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Defects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("DoseG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<decimal>("Grind")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("PourMarkersMs")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<decimal>("TempC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("YieldG")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("BeanId", "Number");

                    b.HasIndex("UserId", "Number")
                        .IsUnique();

                    b.ToTable("brews", (string)null);
                });

            modelBuilder.Entity("Brewbook.Api.Domain.FlavourTag", b =>
                {
                    b.Property<Guid>("BrewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Flavour")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Polarity")
                        .HasColumnType("integer");

                    b.HasKey("BrewId", "Flavour");

                    b.ToTable("flavour_tags", (string)null);
                });

            modelBuilder.Entity("Brewbook.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("OnboardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Brewbook.Api.Domain.Bean", b =>
                {
                    b.HasOne("Brewbook.Api.Domain.User", "User")
                        .WithMany("Beans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Brewbook.Api.Domain.Brew", b =>
                {
                    b.HasOne("Brewbook.Api.Domain.Bean", "Bean")
                        .WithMany("Brews")
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brewbook.Api.Domain.User", "User")
                        .WithMany("Brews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bean");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Brewbook.Api.Domain.FlavourTag", b =>
                {
                    b.HasOne("Brewbook.Api.Domain.Brew", "Brew")
                        .WithMany("FlavourTags")
                        .HasForeignKey("BrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brew");
                });

            modelBuilder.Entity("Brewbook.Api.Domain.Bean", b =>
                {
                    b.Navigation("Brews");
                });

            modelBuilder.Entity("Brewbook.Api.Domain.Brew", b =>
                {
                    b.Navigation("FlavourTags");
                });

            modelBuilder.Entity("Brewbook.Api.Domain.User", b =>
                {
                    b.Navigation("Beans");

                    b.Navigation("Brews");
                });
#pragma warning restore 612, 618
        }
    }
}
